# Generated by Django for netbox_pdu_manager

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import utilities.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0001_initial'),
        ('ipam', '0001_initial'),
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(help_text='PDU identifier name', max_length=100, unique=True)),
                ('manufacturer', models.CharField(default='Raritan', help_text='Manufacturer name', max_length=100)),
                ('model', models.CharField(help_text='Model name (e.g., PX3-5000)', max_length=100)),
                ('serial_number', models.CharField(blank=True, help_text='Serial number', max_length=100)),
                ('pdu_type', models.CharField(default='raritan_px3', help_text='PDU type', max_length=50)),
                ('api_url', models.URLField(blank=True, help_text='Raritan API URL (e.g., https://pdu.example.com/)', max_length=255)),
                ('api_port', models.PositiveIntegerField(default=443, help_text='API port number')),
                ('api_username', models.CharField(blank=True, help_text='API authentication username', max_length=100)),
                ('api_password_ref', models.CharField(blank=True, help_text='API password reference (Secrets integration planned)', max_length=255)),
                ('rack_position', models.PositiveSmallIntegerField(blank=True, help_text='Rack unit position', null=True)),
                ('rated_voltage', models.PositiveIntegerField(help_text='Rated voltage (V)')),
                ('rated_current', models.PositiveIntegerField(help_text='Rated current (A)')),
                ('outlet_count', models.PositiveIntegerField(help_text='Total outlet count')),
                ('phase_count', models.PositiveSmallIntegerField(default=1, help_text='Phase count')),
                ('api_version', models.CharField(blank=True, help_text='Raritan API version (e.g., 4.0.10)', max_length=20)),
                ('firmware_version', models.CharField(blank=True, help_text='Firmware version', max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('ip_address', models.ForeignKey(blank=True, help_text='Management IP address', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pdus', to='ipam.ipaddress')),
                ('rack', models.ForeignKey(blank=True, help_text='Installation rack', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pdus', to='dcim.rack')),
                ('site', models.ForeignKey(help_text='Installation site', on_delete=django.db.models.deletion.PROTECT, related_name='pdus', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'PDU',
                'verbose_name_plural': 'PDUs',
                'ordering': ('site', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('outlet_number', models.PositiveIntegerField(help_text='Outlet number (physical port number)')),
                ('name', models.CharField(blank=True, help_text='Outlet name (custom name)', max_length=100)),
                ('label', models.CharField(blank=True, help_text='Label (physical label)', max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='unknown', help_text='Current power status', max_length=20)),
                ('connected_device_port', models.CharField(blank=True, help_text='Device-side power port name', max_length=50)),
                ('last_measured_voltage', models.FloatField(blank=True, help_text='Last measured voltage (V)', null=True)),
                ('last_measured_current', models.FloatField(blank=True, help_text='Last measured current (A)', null=True)),
                ('last_measured_power', models.FloatField(blank=True, help_text='Last measured power (W)', null=True)),
                ('last_update', models.DateTimeField(blank=True, help_text='Last data update timestamp', null=True)),
                ('bank_number', models.PositiveSmallIntegerField(blank=True, help_text='Bank number (for multi-bank PDUs)', null=True)),
                ('phase', models.CharField(blank=True, help_text='Connected phase', max_length=10)),
                ('connected_device', models.ForeignKey(blank=True, help_text='Connected device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_sources', to='dcim.device')),
                ('pdu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='netbox_pdu_manager.pdu')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Outlet',
                'verbose_name_plural': 'Outlets',
                'ordering': ('pdu', 'outlet_number'),
                'unique_together': {('pdu', 'outlet_number')},
            },
        ),
    ]
